kraft:
  enabled: true

controller:
  replicaCount: 1
  persistence:
    enabled: true
    size: 2Gi
    storageClass: gp2

brokers:
  replicaCount: 1
  controller:
    enabled: false      # 👈 브로커는 컨트롤러 역할 안함
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
  configurationOverrides:
    advertised.listeners: PLAINTEXT://kafka.jhin-eye.svc.cluster.local:9092
  persistence:
    enabled: true
    size: 1Gi
    storageClass: gp2

auth:
  enabled: false
  clientProtocol: plaintext
  interBrokerProtocol: plaintext

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
