replicaCount: 1

auth:
  enabled: false

persistence:
  enabled: true
  storageClass: gp2
  size: 1Gi

zookeeper:
  enabled: true  # 내부 Zookeeper 사용

externalZookeeper:
  enabled: false  # 명시적으로 비활성화

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

extraEnvVars:
  - name: KAFKA_CFG_LISTENERS
    value: PLAINTEXT://:9092
  - name: KAFKA_CFG_ADVERTISED_LISTENERS
    value: PLAINTEXT://kafka.jhin-eye.svc.cluster.local:9092
  - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
    value: PLAINTEXT:PLAINTEXT
  - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
    value: PLAINTEXT
