kraft:
  enabled: true
nodeSelector:
  eks.amazonaws.com/nodegroup: jhin-eye-nodes

controller:
  replicaCount: 1
  persistence:
    enabled: true
    size: 2Gi
    storageClass: gp2-csi
  listeners:
    controller:
      protocol: PLAINTEXT
      containerPort: 9093
      advertisedHost: kafka-controller-0.kafka-controller-headless.jhin-eye.svc.cluster.local
      advertisedPort: 9093

brokers:
  replicaCount: 1
  controller:
    enabled: false
  listeners:
    client:
      name: PLAINTEXT
      protocol: PLAINTEXT
      containerPort: 9092
      advertisedHost: kafka.jhin-eye.svc.cluster.local
      advertisedPort: 9092
    interbroker:
      name: INTERNAL
      protocol: PLAINTEXT
      containerPort: 9094
      advertisedHost: kafka.jhin-eye.svc.cluster.local
      advertisedPort: 9094
  persistence:
    enabled: true
    size: 1Gi
    storageClass: gp2-csi

auth:
  enabled: false
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    mechanisms: []
    interBrokerMechanism: ""
  tls:
    enabled: false

resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1000m
