kraft:
  enabled: false

controller:
  enabled: false
  replicaCount: 0

zookeeper:
  enabled: false

externalZookeeper:
  servers:
    - zookeeper.jhin-eye.svc.cluster.local

auth:
  enabled: false

persistence:
  enabled: true
  storageClass: gp2
  size: 1Gi

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
