# KRaft 모드 활성화 (Zookeeper 제거)
kraft:
  enabled: true

# 컨트롤러 구성 (KRaft 모드 필수)
controller:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: gp2
    size: 2Gi

brokers:
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi
    storageClass: gp2


auth:
  enabled: false

persistence:
  enabled: true
  storageClass: gp2
  size: 1Gi

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
