# 기존엔 여기 minimal 설정만 있었을 텐데…

image:
  repository: bitnami/kafka
  tag: 3.7.1

# ↓↓↓ 아래 블록을 추가 ↓↓↓

kraft:
  enabled: true
  clusterId: "jhinClusterId001"

controller:
  replicaCount: 1
  broker:
    enabled: true
  configurationOverrides:
    server.properties: |-
      auto.create.topics.enable=false
      offsets.topic.replication.factor=1
      transaction.state.log.replication.factor=1
      controller.quorum.voters=0@kafka-controller-0.kafka-controller-headless.jhin-eye.svc.cluster.local:9093
  persistence:
    enabled: true
    size: 2Gi
    storageClass: gp2-csi

brokers:
  replicaCount: 1
  configurationOverrides:
    server.properties: |-
      auto.create.topics.enable=false
      offsets.topic.replication.factor=1
      transaction.state.log.replication.factor=1
  persistence:
    enabled: true
    size: 1Gi
    storageClass: gp2-csi

auth:
  enabled: false

nodeSelector:
  eks.amazonaws.com/nodegroup: jhin-eye-nodes

listeners:
  client:
    protocol: PLAINTEXT

configurationOverrides:
  advertised.listeners: |
    PLAINTEXT://kafka.jhin-eye.svc.cluster.local:9092
