replicaCount: 1

auth:
  enabled: false  # ✅ 이건 필수지만 이것만으론 부족함

zookeeper:
  enabled: true

externalZookeeper:
  enabled: false

persistence:
  enabled: true
  storageClass: gp3
  size: 1Gi

# 핵심 설정: 명시적으로 PLAINTEXT만 사용
config:
  listeners: PLAINTEXT://:9092
  advertised.listeners: PLAINTEXT://kafka.jhin-eye.svc.cluster.local:9092
  listener.security.protocol.map: PLAINTEXT:PLAINTEXT
  inter.broker.listener.name: PLAINTEXT
  security.inter.broker.protocol: PLAINTEXT

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
