replicaCount: 1

image:
  tag: 3.7.0

zookeeper:
  enabled: false  # 이미 배포한 zookeeper 사용

externalZookeeper:
  servers:
    - zookeeper.jhin-eye.svc.cluster.local

persistence:
  enabled: true
  size: 2Gi
  storageClass: gp2

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
