architecture: standalone

master:
  persistence:
    enabled: true
    storageClass: gp2
    size: 1Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 250m
