apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: jhin-cluster
  namespace: jhin-eye
  annotations:
    strimzi.io/kraft: enabled  # Enable KRaft (ZooKeeper-less) mode
spec:
  kafka:
    version: 4.0.0
    replicas: 1                # Single broker
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false               # PLAINTEXT listener
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
