name: Deploy PostgreSQL to EKS

on:
  push:
    tags:
      - 'postgres-v*'  # 예: postgresql 배포를 위한 태그는 postres-v0.1.0 등으로


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.3  # 또는 latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Update kubeconfig for EKS
      run: aws eks update-kubeconfig --region ap-northeast-2 --name jhin-eye

    - name: Add Bitnami Helm Repo
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update

    - name: Deploy PostgreSQL with Helm
      run: |
        helm upgrade --install jhineye-postgres bitnami/postgresql \
          --namespace jhin-eye \
          --create-namespace \
          -f postgresql/values/values.yaml \
          --set auth.password=${{ secrets.POSTGRES_PASSWORD }}
